CREATE TABLE bots.Sockets
(
    ID SERIAL PRIMARY KEY,
    Host VARCHAR(50) NOT NULL,
    Port INT NOT NULL,
    Request JSONB NOT NULL, 
    Handshake VARCHAR(50),
    Topic VARCHAR(50) NOT NULL,
    ClientType VARCHAR(50) NOT NULL,
    Pid Int NOT NULL,
    State VARCHAR(50) NOT NULL,
    CreatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)
);
